### ISSUE TITLE
Add classes to animated elements

### ISSUE THREAD

**Issue by esamattis** [fgnass/spin.js#107]
It would allow setting the color directly from CSS.

**Comment by andreyvolokitin** [comment]
Could we now reconsider this?

**Comment by theodorejb** [comment]
@andreyvolokitin What class(es) do you think should be added? I believe it's already possible to target the spinner lines in CSS via `.spinner > div > div`.

**Comment by andreyvolokitin** [comment]
It's possible, but I think only with a help of `!important` (which is generally a bad practice), since all styles are applied inline currently. I thought about at least 1 class for changing a color of spinner lines (something like `.{className}__line`), but I'm not familiar with `spin.js` specifics and maybe more classes could be helpful. 

On the other hand, maybe `.spinner > div > div` with `!important` wouldn't cause any problems and could be sufficient...

**Comment by theodorejb** [comment]
> maybe `.spinner > div > div` with `!important` wouldn't cause any problems and could be sufficient.

I actually do this myself in a couple projects (in order to override the spinner color when dark mode is enabled). I don't think there's anything wrong with this approach. Even if there was a separate CSS class for the lines, `!important` would be necessary to override inline styles.

**Comment by andreyvolokitin** [comment]
I thought that styles which are prone to change (like `background-color`) would become external in case of classes. If they remain inline there is indeed no point in classes

**Comment by theodorejb** [comment]
The styles are inline because they can be set dynamically in the spinner options (e.g. using an array of colors causing each line to be a different color).
