### ISSUE TITLE
Slow on LG-P700 smart phone

### ISSUE THREAD

**Issue by thehappycoder** [fgnass/spin.js#200]
I hooked up the slow lg (LG-P700) android phone with the desktop's google chrome 33 beta to find out why is it working slow on my page.

To my surprize, there is a lot of long running "rasterize" events and they happen in parallel with the rest of the events (like js and rendering).

Here is the exported timeline data: https://gist.github.com/thehappycoder/a089562b13e028766e82/raw/53f0425c5f4756c7f5c7662711c4e4d3c6d3ba56/TimelineRawData-20140130T152139.json

After series of tests I figured out that spin.js creates all this. Is there a lighter version of spin.js for such devices? I don't want to use gif because the background is not solid.

**Comment by TimothyGu** [comment]
First, unfortunately I can no longer read the JSON file as Chrome complains about it being "old format."

I have noticed the performance problem, since we are animating multiple lines as different objects. It might be more feasible to just animate the entire spinner as a whole. Let's move this discussion to #215 since this issue affects many devices and browsers than just LG-P700 with Chrome.
