### ISSUE TITLE
No spinning on Safari after dynamic stylesheet change

### ISSUE THREAD

**Issue by robneild** [fgnass/spin.js#262]
I have a problem that only affected Safari. The spinner doesn't spin.
I debugged it down to be related to some dynamic stylesheet change modifiction code I am doing before creating the spinner. The following page reproduced it for me.

``` html
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript" src="/nc/external/spin.js"></script>
<link rel="alternate stylesheet" type="text/css" href="/dummy/not/important.css"/>

<script>
function runOnLoad() {

    var styleSheet = document.getElementsByTagName("link")[0];
    styleSheet.disabled = true;

    var spinner = new Spinner().spin(document.body);
}

</script>
</head>
<body onload='runOnLoad()'>
</body>
</html>
```

There are a couple of workarounds
- Modifying spinner code so never uses css animations
- Add a second pause before I create the spinner
- Make the stylesheet start disabled, then enable it

I'm using Safari 7.1

**Comment by jronimo** [comment]
I have experienced a similar, but not identical, issue to the one cited by the OP - although, I think there's a chance the issues are related. 

The following relates to,

    spin.js 			2.0.1,
    Chrome 		39.0.2171.95,
    IE 			11.0.9600.17416,
    Firefox 		34.0.5

Unless specifically highlighted, the description below applies to all of the above.

I am using spin.js to provide a 'wait-animation' on a glass pane (an opaque div, which I call the 'wait-screen') that is shown after submitting a form. I am developing a single page application that shows numerous screens, including the wait-screen. To be clear, the wait-screen, contains a wait-display (the element passed to spin.js), which contains the wait-animation provided by spin.js.

The first versions of my single page application statically included CSS files via &lt;link&gt; elements hard-coded into the page. I then converted the application such that the single page did not include the bulk of the CSS via &lt;link&gt;  elements. Instead, it appended the contents of CSS files to the document after the document had completed its load (as signified by the document's onload event).

Prior to the conversion, the wait-animation worked as expected. After the conversion, the wait-display showed up, but the wait-animation did not animate - i.e. no spinning. 

The wait-screen and the wait-display elements are in a hierarchy of document elements citing CSS class names cited in the dynamically included CSS. As part of working my way through this issue, I added to the body of the same page the element &lt;div id="myDiv"&gt; and styled the div with the following so that I could see it,

#myDiv {
    position: absolute; left: 100px, top: 100px, width: 100px, height: 100px; background-color: white;
}

I specified this CSS in either of the following locations, and the results were the same for both locations: (i) in a CSS file statically included in the document via a &lt;link&gt; element hardcoded in the page, and (ii) in a CSS file whose contents were dynamically added to the document after document load.

After page load, I passed myDiv to spin.js, specifying the same options instance as used for the wait-screen. The animation in myDiv worked perfectly, while the animation on the wait-screen continued to be displayed but not spinning - I was able to view both simultaneously. Both display in the way specified by the options passed to spin.js but only myDiv shows the spinning animation. (Note: In Firefox, myDiv did not animate, and it did not matter where I put the CSS for myDiv. However, Chrome and IE worked as described.)

As a work-around, I was able to get the animation working in my wait-screen by commenting out the following (in spin.js), thus ensuring useCssAnimations was undefined.

	/*
	if(!vendor(probe, 'transform') && probe.adj) initVML();
	else useCssAnimations = vendor(probe, 'animation');
	*/

The wait-animation worked as expected in all browsers with these lines commented out.

Moving forward, I'll just run with the commented out code as a solution, so I'm good to go. But I'll keep an eye on this thread for your comments.

Thanks for putting together this great little plugin.

Here is how I'm dynamically adding CSS to the document,

	function addDocumentCss(cssText) {
	
		var head = window.document.head || window.document.getElementsByTagName('head')[0];
		var style = document.createElement('style');
	
		style.setAttribute('type', 'text/css');
		style.setAttribute('media', 'screen');
		style.textContent = cssText;        // We're targeting IE10+, so this is ok.
	
		head.appendChild(style);
	}

Cheers.

**Comment by TimothyGu** [comment]
@jronimo, thanks for your insights. It'll be great if you can give a **stand-alone** sample HTML file for me to test. Disabling `useCssAnimations` means that a very inefficient `setTimeout()` mechanism is used, which might offer better compatibility. Spin.js does do some funky things like appending styles to `<head>` when CSS animations are used, so that might be a reason for this bug.

**Comment by jronimo** [comment]
Hi

Thanks for getting back to me on this. My original message was a few months ago and I'm not in a position to give you a standalone page immediately, but I will definitely try to get that to you in the next week or so as I'm still interested in an outcome.

Thanks again for replying.

Cheers.

**Comment by TimothyGu** [comment]
@jronimo okay no problem. I just picked up the maintainership of this project a few days ago so just trying to clean up rotting bug reports, pull requests, et cetera.

**Comment by ErrolSayre** [comment]
I'm encountering this issue in a page bundled within an iOS app used within a UIWebView. I was able to utilize the same hack to solve my problem but wanted to check-in to see if this could be solved?

Could another option (rather than setTimeout) be to use requestAnimationFrame()?

**Comment by TimothyGu** [comment]
@ErrolSayre, can you provide a sample HTML?

**Comment by TimothyGu** [comment]
> Could another option (rather than setTimeout) be to use requestAnimationFrame()?

Yes I would think so.

**Comment by ErrolSayre** [comment]
I'll see if I can. I do know that I never have had the problem in my HTML file within Safari on the Mac while developing it. I specifically encountered the issue on iOS in my app within a UIWebView. It'll be a couple weeks before I could do this though as I can't take effort away from getting the app out and on the store.

Suffice to say, removing the support for CSS Animations did resolve my problem and I haven't noticed any issues with my app's performance during that small time when the indicator is animating.

**Comment by allansli** [comment]
Any update on this?

**Comment by theodorejb** [comment]
This should be fixed in spin.js v3.0.
