### ISSUE TITLE
Allow specification of 2nd color

### ISSUE THREAD

**Issue by iangilman** [fgnass/spin.js#30]
Right now you can specify the "on" color, but it always fades to the same "off" color: transparent. I would like to be able to specify the "off" color, so I can make a spinner that for instance fades from #ccc to #333, and will therefore be visible over a wide variety of backgrounds (without having to use a shadow).

**Comment by tremby** [comment]
I was looking for this too.

**Comment by fgnass** [comment]
Hm, a `minOpacity` setting would be much easier to implement than a second color. Would that work for you too?

**Comment by tremby** [comment]
Isn't the existing opacity option actually a `minopacity`?

No, it wouldn't do the trick in my case. I want to fade from opaque red to mostly transparent white. Having "active" and "inactive" colours would do it, if they can be specified in rgba format. Spin.js would just interpolate between the two, or leave that up to a CSS transition if practical.

**Comment by fgnass** [comment]
You're right, the opacity setting already does exactly that. Unfortunately
the feature you're looking for can't be done in spin.js as one of our main
design goals is to deliver the same visual result, no matter if rendered
via VML or DIVs. The amount of code needed to interpolate rgba colors and
map them back to #rrggbb + opacity for VML would conflict with our second
goal: to have a file size not larger than an animated gif.

This would better fit into a project that offers a CSS-only solution. Such
a project could also offer to output static CSS/Sass code. Not sure if a
tool like this already exists – if you find one, please post the link here
so that we can refer to it whenever people ask for similar features.

Bart Nagel <notifications@github.com> schrieb am Do., 1. Okt. 2015 um 08:55:

**Comment by theodorejb** [comment]
It is now possible to specify a `fadeColor` option in spin.js v3.1.0.

For example, using a fade color of "violet" with a light blue line color produces an effect like this:
![fadecolor example](https://user-images.githubusercontent.com/3053271/33244045-033c1dd6-d2b6-11e7-8469-fec20e379b6d.PNG)
