### ISSUE TITLE
Allow control of shadow

### ISSUE THREAD

**Issue by pistachiomatt** [fgnass/spin.js#35]
Sometimes I may want to tone down the shadow, or use a white-inset shadow. As an improvement, allow us to control the shadow.

**Comment by theodorejb** [comment]
At first I thought it would be easy to directly apply a box-shadow to the spinner lines. The problem with this is that the shadow is rotated along with the lines, which doesn't look natural:

![direct box-shadow](https://user-images.githubusercontent.com/3053271/33236405-172a9122-d218-11e7-8ce0-6d6fd1a92444.PNG)

The current code avoids this by generating another element for each line, coloring it black and applying a black box-shadow, and then positioning it down a couple pixels beneath the line. Unfortunately, this makes it difficult to customize the shadow position and color, and as far as I can tell impossible to support inset shadows, or multiple blended shadows with different positions.

Thankfully, I've discovered a better solution. Users could pass a standard box-shadow value in the spinner options, and it would be parsed to determine the x/y offsets. Then trigonometry can be used to correct the shadow coordinates for each line based on its degrees of rotation, so the shadows appear to be caused by the same light source:

![fixed box-shadow](https://user-images.githubusercontent.com/3053271/33236447-937de368-d219-11e7-9740-0f5bb2f27720.PNG)

I have a working implementation of this in pull request #346.
